version: '1.0'

volumes:
  db-data:
    driver: local

services:

  postgres:
    image: postgres:11.13
    container_name: t1_java_demo
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=course_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    volumes:
      - db-data:/var/lib/postgresql/data
